/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import { useGLTF } from "@react-three/drei";
import React, { useRef } from "react";
import { DissolveMaterial } from "./DissolveMaterial";

export function Table(props) {
  const group = useRef();
  const { nodes, materials } = useGLTF(
    "https://vazxmixjsiawhamofees.supabase.co/storage/v1/object/public/models/table-wood/model.gltf"
  );
  return (
    <group ref={group} {...props} dispose={null}>
      <mesh geometry={nodes.tableLarge.geometry} rotation={[Math.PI / 2, 0, 0]}>
        <DissolveMaterial
          baseMaterial={materials["BrownDark.074"]}
          visible={props.dissolveVisible}
          onFadeOut={props.onFadeOut}
          color="#7f532f"
        />
      </mesh>
    </group>
  );
}

useGLTF.preload(
  "https://vazxmixjsiawhamofees.supabase.co/storage/v1/object/public/models/table-wood/model.gltf"
);
